name: Docker Image CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setting up .env
        run: |
          echo "${{ secrets.SCHEDULE_PRODUCTION_ENV }}" > .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate timestamp-based tag
        id: tag
        run: echo "TIMESTAMP_TAG=$(date +'%y%m%d')" >> $GITHUB_ENV

      - name: Build Docker image (Laravel)
        run: |
          docker build --no-cache -t ivan/scheduleapp:${{ env.TIMESTAMP_TAG }} .

      - name: Build Docker image (Nginx)
        run: |
          docker build --no-cache -t ivan/schedulenginx:${{ env.TIMESTAMP_TAG }} ./docker/nginx


      - name: Docker push images
        run: |
          docker push ivan/scheduleapp:${{ env.TIMESTAMP_TAG }}
          docker push ivan/schedulenginx:${{ env.TIMESTAMP_TAG }}

      - name: Scan JavaScript dependencies for vulnerabilities with npm audit
        run: npm audit --audit-level=high


     
   

     
    
                  

       
    
        

